import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './app.css';
import SideDrawer from './ui/SideDrawer';
import Navbar from './ui/Navbar';

const roboto = Roboto({ weight: '400', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div className="drawer lg:drawer-open">
          <input id="drawer" type="checkbox" className="drawer-toggle" />
          <SideDrawer />
          <div className="drawer-content ml-4 max-w-screen">
            <Navbar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
